### ISSUE TITLE
ImportError: cannot import name transport

### ISSUE THREAD

**Issue by saatomic** [ShawnDEvans/smbmap#17]
I've installed impacket and tried to run smbmap.

```
root@kali:~/smbmap-master# python smbmap.py
Traceback (most recent call last):
  File "smbmap.py", line 17, in <module>
    from impacket.dcerpc import transport, svcctl, srvsvc
ImportError: cannot import name transport
```

As it seems this project is dead - but you never know.

**Comment by cyian-1756** [comment]
have you tried `pip install transport` ?

**Comment by joshcomplex** [comment]
This is actually ties to the version of impacket. Try installing impacket
version 0.9.13

**Comment by stillinsecure** [comment]
Installing impacket 0.9.13 fixed it for me.

**Comment by ShawnDEvans** [comment]
This is sorta kinda dead? I'm lazy and busy, which is a horrible combo for supporting a tool haha.  In any case, I'll try to get these issues ironed out.  I use this in a Kali time capsule VM to avoid doing things like fixing problems.  I'll update Impacket and get the fix pushed within the next week.  And because I said this on the Internet, maybe it'll actually happen. 

I highly encourage anyone who uses or has used SMBMap to check out CrackMapExec.  It does everything SMBMap does and 1000x more.  Seriously awesome tool :)

https://github.com/byt3bl33d3r/CrackMapExec

**Comment by saatomic** [comment]
ohwow. I didn't expect that. Thank you for your feedback and the link!

**Comment by mechgt** [comment]
I'm going to get on "me too" bandwagon.  This is a very cool tool.  I found it as it was featured in some B2R walkthroughs.  Anyway, nice tool and would love to see it updated for basic out of the box compatibility.  Thanks!!

**Comment by ShawnDEvans** [comment]
Just to provide an update, I have a version of the tool that is working with the latest greatest Impact (.9.16 i do believe).  I'm going to test it on an pen test today and tomorrow. If all goes well I'll push the changes!

**Comment by mechgt** [comment]
Great, thanks!!!  Confirmed this is working on my version of Kali with impacket 0.9.13-0kali1
