### ISSUE TITLE
[!] Bummer: local variable 'priv_status' referenced before assignment

### ISSUE THREAD

**Issue by relector-tuxnix** [ShawnDEvans/smbmap#84]
Latest version (git head) needs to declare and assign value to 'priv_status' :
![priv_status](https://github.com/ShawnDEvans/smbmap/assets/1979197/3c78e7d9-d7dd-4c7e-887d-ef320e7da393)

**Comment by ShawnDEvans** [comment]
Nuts, I'm not even sure that code path should be executing. I'm booked this
week, but will try to get to it next week. Thanks for the report!!

**Comment by ShawnDEvans** [comment]
I made sure the priv_status var was declared. Thanks again!

**Comment by relector-tuxnix** [comment]
Nice work. Thanks :+1:

**Comment by shaaati** [comment]
It seems that you pushed the fix for this issue after releasing v1.9.1 (even though it was before you increased the version number).

This results in Kali Linux (which in turn just uses the package from Debian Testing) showing an smbmap version of v1.9.1 which still is affected by this bug.

As far as "I'm not even sure that code path should be executing": I encountered this on two recent penetration testing assignments.
While the "buggy" package worked against a Synology NAS, it failed when trying to list SMB shares on a Windows domain controller.

Would it be possible to simply push a new bugfix release that incorporates the fix, which would then be used by Debian as the source for a new package?

**Comment by felix4webscience** [comment]
Hi, any news about the issue recalled by @shaaati? I run into the same problem...

**Comment by shaaati** [comment]
Looks good to me. It seems you pushed 1.9.2 the same day I made my comment. Maybe that overlapped. I guess the next step is to get Debian to build a new package based on 1.9.2, but there's nothing that you need to do.
